package com.xc.study.common;

public enum ErrorCode {
    SUCCESS("SUCCESS"),
    BAD_REQUEST("BAD_REQUEST"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    NOT_FOUND("NOT_FOUND"),
    CONFLICT("CONFLICT"),
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS"),
    AUTH_ACCOUNT_DISABLED("AUTH_ACCOUNT_DISABLED"),
    AUTH_CLIENT_NOT_ALLOWED("AUTH_CLIENT_NOT_ALLOWED"),
    AUTH_TOKEN_INVALID("AUTH_TOKEN_INVALID"),
    AUTH_TOKEN_EXPIRED("AUTH_TOKEN_EXPIRED"),
    MEMBERSHIP_REQUIRED("MEMBERSHIP_REQUIRED"),
    CLASSROOM_PERMISSION_DENIED("CLASSROOM_PERMISSION_DENIED"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    INTERNAL_ERROR("INTERNAL_ERROR");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
