create table if not exists user_vocab_item_progress (
  id bigint generated by default as identity,
  user_id bigint not null,
  vocab_list_id bigint not null,
  vocab_item_id bigint not null,
  status varchar(30) not null default 'learned',
  review_count integer not null default 0,
  learned_at timestamptz,
  last_reviewed_at timestamptz,
  next_review_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_user_vocab_item_progress primary key (id),
  constraint fk_user_vocab_item_progress_user foreign key (user_id) references users(id),
  constraint fk_user_vocab_item_progress_list foreign key (vocab_list_id) references vocab_lists(id),
  constraint fk_user_vocab_item_progress_item foreign key (vocab_item_id) references vocab_items(id),
  constraint uq_user_vocab_item_progress_user_list_item unique (user_id, vocab_list_id, vocab_item_id),
  constraint ck_user_vocab_item_progress_status check (status in ('learning', 'learned', 'reviewing', 'mastered')),
  constraint ck_user_vocab_item_progress_review_count check (review_count >= 0)
);

comment on table user_vocab_item_progress is '用户词汇条目学习进度表';
comment on column user_vocab_item_progress.id is '条目进度 ID';
comment on column user_vocab_item_progress.user_id is '用户 ID';
comment on column user_vocab_item_progress.vocab_list_id is '词汇表 ID';
comment on column user_vocab_item_progress.vocab_item_id is '词汇 ID';
comment on column user_vocab_item_progress.status is '学习状态：learning/learned/reviewing/mastered';
comment on column user_vocab_item_progress.review_count is '复习次数';
comment on column user_vocab_item_progress.learned_at is '首次学会时间';
comment on column user_vocab_item_progress.last_reviewed_at is '最近复习时间';
comment on column user_vocab_item_progress.next_review_at is '下次复习时间';
comment on column user_vocab_item_progress.created_at is '创建时间';
comment on column user_vocab_item_progress.updated_at is '更新时间';

create index if not exists idx_user_vocab_item_progress_user_list on user_vocab_item_progress(user_id, vocab_list_id);
create index if not exists idx_user_vocab_item_progress_item on user_vocab_item_progress(vocab_item_id);
create index if not exists idx_user_vocab_item_progress_status on user_vocab_item_progress(status);

insert into user_vocab_item_progress (
  user_id,
  vocab_list_id,
  vocab_item_id,
  status,
  review_count,
  learned_at,
  last_reviewed_at,
  created_at,
  updated_at
)
select
  progress.user_id,
  progress.vocab_list_id,
  ranked_items.id,
  'learned',
  1,
  coalesce(progress.updated_at, progress.created_at, now()),
  coalesce(progress.updated_at, progress.created_at, now()),
  coalesce(progress.created_at, now()),
  coalesce(progress.updated_at, progress.created_at, now())
from user_vocab_progress progress
join (
  select
    item.id,
    item.vocab_list_id,
    row_number() over (partition by item.vocab_list_id order by item.sort_order asc, item.id asc) as item_rank
  from vocab_items item
  where item.status = 'active'
) ranked_items on ranked_items.vocab_list_id = progress.vocab_list_id
where ranked_items.item_rank <= progress.reviewed_count
on conflict (user_id, vocab_list_id, vocab_item_id) do nothing;
