create table if not exists user_sentence_progress (
  id bigint generated by default as identity,
  user_id bigint not null,
  exercise_set_id bigint not null,
  sentence_exercise_id bigint not null,
  status varchar(30) not null default 'learning',
  attempt_count integer not null default 0,
  correct_count integer not null default 0,
  learned_at timestamptz,
  last_practiced_at timestamptz,
  last_correct_at timestamptz,
  next_review_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_user_sentence_progress primary key (id),
  constraint fk_user_sentence_progress_user foreign key (user_id) references users(id),
  constraint fk_user_sentence_progress_set foreign key (exercise_set_id) references exercise_sets(id),
  constraint fk_user_sentence_progress_exercise foreign key (sentence_exercise_id) references sentence_exercises(id),
  constraint uq_user_sentence_progress_user_exercise unique (user_id, sentence_exercise_id),
  constraint ck_user_sentence_progress_status check (status in ('learning', 'learned', 'reviewing', 'mastered')),
  constraint ck_user_sentence_progress_counts check (attempt_count >= 0 and correct_count >= 0 and correct_count <= attempt_count)
);

comment on table user_sentence_progress is '用户句子题学习进度表';
comment on column user_sentence_progress.id is '句子进度 ID';
comment on column user_sentence_progress.user_id is '用户 ID';
comment on column user_sentence_progress.exercise_set_id is '题组 ID';
comment on column user_sentence_progress.sentence_exercise_id is '句子题 ID';
comment on column user_sentence_progress.status is '学习状态：learning/learned/reviewing/mastered';
comment on column user_sentence_progress.attempt_count is '作答次数';
comment on column user_sentence_progress.correct_count is '答对次数';
comment on column user_sentence_progress.learned_at is '首次答对时间';
comment on column user_sentence_progress.last_practiced_at is '最近练习时间';
comment on column user_sentence_progress.last_correct_at is '最近答对时间';
comment on column user_sentence_progress.next_review_at is '下次复习时间';
comment on column user_sentence_progress.created_at is '创建时间';
comment on column user_sentence_progress.updated_at is '更新时间';

create index if not exists idx_user_sentence_progress_user_set on user_sentence_progress(user_id, exercise_set_id);
create index if not exists idx_user_sentence_progress_exercise on user_sentence_progress(sentence_exercise_id);
create index if not exists idx_user_sentence_progress_status on user_sentence_progress(status);

insert into user_sentence_progress (
  user_id,
  exercise_set_id,
  sentence_exercise_id,
  status,
  attempt_count,
  correct_count,
  learned_at,
  last_practiced_at,
  last_correct_at,
  created_at,
  updated_at
)
select
  attempts.user_id,
  exercises.exercise_set_id,
  attempts.exercise_id,
  case when sum(case when attempts.is_correct then 1 else 0 end) > 0 then 'learned' else 'learning' end,
  count(*)::integer,
  sum(case when attempts.is_correct then 1 else 0 end)::integer,
  min(attempts.answered_at) filter (where attempts.is_correct),
  max(attempts.answered_at),
  max(attempts.answered_at) filter (where attempts.is_correct),
  min(coalesce(attempts.created_at, attempts.answered_at, now())),
  max(coalesce(attempts.updated_at, attempts.answered_at, now()))
from exercise_attempts attempts
join sentence_exercises exercises on exercises.id = attempts.exercise_id
group by attempts.user_id, exercises.exercise_set_id, attempts.exercise_id
on conflict (user_id, sentence_exercise_id) do nothing;
