-- Core schema for XC Chinese Learning Platform.
-- Status and enum values are documented in ../ENUMS.md.

create table if not exists users (
  id bigint generated by default as identity,
  email varchar(255) not null,
  password_hash varchar(255) not null,
  nickname varchar(100),
  status varchar(30) not null default 'active',
  trial_started_at timestamptz,
  trial_ends_at timestamptz,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_users primary key (id),
  constraint uq_users_email unique (email),
  constraint ck_users_status check (status in ('active', 'disabled', 'deleted'))
);

comment on table users is '前台用户表';
comment on column users.id is '用户 ID';
comment on column users.email is '邮箱，登录账号';
comment on column users.password_hash is '密码哈希';
comment on column users.nickname is '昵称';
comment on column users.status is '用户状态：active/disabled/deleted';
comment on column users.trial_started_at is '试用开始时间';
comment on column users.trial_ends_at is '试用结束时间';
comment on column users.last_login_at is '最近登录时间';
comment on column users.created_at is '创建时间';
comment on column users.updated_at is '更新时间';

create index if not exists idx_users_status on users(status);

create table if not exists user_preferences (
  id bigint generated by default as identity,
  user_id bigint not null,
  ui_language varchar(10) not null default 'zh',
  translation_language varchar(10) not null default 'ru',
  vocab_meaning_language varchar(10) not null default 'ru',
  matching_meaning_language varchar(10) not null default 'ru',
  sound_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_user_preferences primary key (id),
  constraint fk_user_preferences_user foreign key (user_id) references users(id),
  constraint uq_user_preferences_user unique (user_id),
  constraint ck_user_preferences_ui_language check (ui_language in ('zh', 'ru', 'en')),
  constraint ck_user_preferences_translation_language check (translation_language in ('ru', 'en')),
  constraint ck_user_preferences_vocab_language check (vocab_meaning_language in ('ru', 'en')),
  constraint ck_user_preferences_matching_language check (matching_meaning_language in ('ru', 'en'))
);

comment on table user_preferences is '用户偏好表';
comment on column user_preferences.id is '偏好 ID';
comment on column user_preferences.user_id is '用户 ID';
comment on column user_preferences.ui_language is '界面语言：zh/ru/en';
comment on column user_preferences.translation_language is '练习翻译语言：ru/en';
comment on column user_preferences.vocab_meaning_language is '词汇释义语言：ru/en';
comment on column user_preferences.matching_meaning_language is '连连看释义语言：ru/en';
comment on column user_preferences.sound_enabled is '连连看音效是否开启';
comment on column user_preferences.created_at is '创建时间';
comment on column user_preferences.updated_at is '更新时间';

create table if not exists membership_plans (
  id bigint generated by default as identity,
  name varchar(100) not null,
  duration_days integer not null,
  duration_unit varchar(20) not null default 'day',
  duration_value integer not null,
  price numeric(10, 2) not null,
  currency varchar(10) not null default 'CNY',
  status varchar(30) not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_membership_plans primary key (id),
  constraint ck_membership_plans_duration_days check (duration_days > 0),
  constraint ck_membership_plans_duration_unit check (duration_unit in ('day', 'month', 'custom')),
  constraint ck_membership_plans_duration_value check (duration_value > 0),
  constraint ck_membership_plans_price check (price >= 0),
  constraint ck_membership_plans_status check (status in ('active', 'inactive'))
);

comment on table membership_plans is '会员套餐表';
comment on column membership_plans.id is '套餐 ID';
comment on column membership_plans.name is '套餐名称';
comment on column membership_plans.duration_days is '有效天数，最终权限计算使用';
comment on column membership_plans.duration_unit is '时长单位：day/month/custom';
comment on column membership_plans.duration_value is '时长数值，如 1 个月、3 个月';
comment on column membership_plans.price is '套餐价格';
comment on column membership_plans.currency is '币种';
comment on column membership_plans.status is '套餐状态：active/inactive';
comment on column membership_plans.created_at is '创建时间';
comment on column membership_plans.updated_at is '更新时间';

create index if not exists idx_membership_plans_status on membership_plans(status);

create table if not exists admin_users (
  id bigint generated by default as identity,
  username varchar(100) not null,
  password_hash varchar(255) not null,
  display_name varchar(100),
  status varchar(30) not null default 'active',
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_admin_users primary key (id),
  constraint uq_admin_users_username unique (username),
  constraint ck_admin_users_status check (status in ('active', 'disabled'))
);

comment on table admin_users is '后台管理员表';
comment on column admin_users.id is '管理员 ID';
comment on column admin_users.username is '登录名';
comment on column admin_users.password_hash is '密码哈希';
comment on column admin_users.display_name is '显示名称';
comment on column admin_users.status is '管理员状态：active/disabled';
comment on column admin_users.last_login_at is '最近登录时间';
comment on column admin_users.created_at is '创建时间';
comment on column admin_users.updated_at is '更新时间';

create index if not exists idx_admin_users_status on admin_users(status);

create table if not exists user_memberships (
  id bigint generated by default as identity,
  user_id bigint not null,
  plan_id bigint,
  started_at timestamptz not null,
  ends_at timestamptz not null,
  source varchar(30) not null default 'payment',
  adjusted_by_admin_id bigint,
  adjust_reason text,
  status varchar(30) not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_user_memberships primary key (id),
  constraint fk_user_memberships_user foreign key (user_id) references users(id),
  constraint fk_user_memberships_plan foreign key (plan_id) references membership_plans(id),
  constraint fk_user_memberships_adjusted_by foreign key (adjusted_by_admin_id) references admin_users(id),
  constraint ck_user_memberships_period check (ends_at > started_at),
  constraint ck_user_memberships_source check (source in ('payment', 'admin_adjustment')),
  constraint ck_user_memberships_status check (status in ('active', 'expired', 'cancelled'))
);

comment on table user_memberships is '用户会员表';
comment on column user_memberships.id is '会员记录 ID';
comment on column user_memberships.user_id is '用户 ID';
comment on column user_memberships.plan_id is '套餐 ID，可为空';
comment on column user_memberships.started_at is '会员开始时间';
comment on column user_memberships.ends_at is '会员结束时间';
comment on column user_memberships.source is '来源：payment/admin_adjustment';
comment on column user_memberships.adjusted_by_admin_id is '后台调整管理员 ID';
comment on column user_memberships.adjust_reason is '后台调整原因';
comment on column user_memberships.status is '会员状态：active/expired/cancelled';
comment on column user_memberships.created_at is '创建时间';
comment on column user_memberships.updated_at is '更新时间';

create index if not exists idx_user_memberships_user_status on user_memberships(user_id, status, ends_at);
create index if not exists idx_user_memberships_plan on user_memberships(plan_id);
create index if not exists idx_user_memberships_adjusted_by on user_memberships(adjusted_by_admin_id);

create table if not exists payment_orders (
  id bigint generated by default as identity,
  order_no varchar(64) not null,
  user_id bigint not null,
  plan_id bigint not null,
  amount numeric(10, 2) not null,
  currency varchar(10) not null default 'CNY',
  provider varchar(50) not null,
  client_type varchar(30) not null,
  payment_url varchar(500),
  provider_trade_no varchar(128),
  status varchar(30) not null default 'pending',
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_payment_orders primary key (id),
  constraint uq_payment_orders_order_no unique (order_no),
  constraint fk_payment_orders_user foreign key (user_id) references users(id),
  constraint fk_payment_orders_plan foreign key (plan_id) references membership_plans(id),
  constraint ck_payment_orders_amount check (amount >= 0),
  constraint ck_payment_orders_provider check (provider in ('wechat_pay', 'alipay')),
  constraint ck_payment_orders_client_type check (client_type in ('web', 'mobile', 'admin')),
  constraint ck_payment_orders_status check (status in ('pending', 'paid', 'failed', 'refunded'))
);

comment on table payment_orders is '支付订单表';
comment on column payment_orders.id is '订单 ID';
comment on column payment_orders.order_no is '订单号';
comment on column payment_orders.user_id is '用户 ID';
comment on column payment_orders.plan_id is '套餐 ID';
comment on column payment_orders.amount is '订单金额';
comment on column payment_orders.currency is '币种';
comment on column payment_orders.provider is '支付渠道：wechat_pay/alipay';
comment on column payment_orders.client_type is '客户端类型：web/mobile/admin';
comment on column payment_orders.payment_url is '支付链接或二维码地址';
comment on column payment_orders.provider_trade_no is '第三方交易号';
comment on column payment_orders.status is '订单状态：pending/paid/failed/refunded';
comment on column payment_orders.paid_at is '支付时间';
comment on column payment_orders.created_at is '创建时间';
comment on column payment_orders.updated_at is '更新时间';

create index if not exists idx_payment_orders_user_status on payment_orders(user_id, status, created_at);
create index if not exists idx_payment_orders_plan on payment_orders(plan_id);
create index if not exists idx_payment_orders_provider_trade_no on payment_orders(provider, provider_trade_no);

create table if not exists payment_notifications (
  id bigint generated by default as identity,
  order_id bigint,
  provider varchar(50) not null,
  provider_trade_no varchar(128),
  notify_payload jsonb,
  signature_valid boolean not null default false,
  handled boolean not null default false,
  received_at timestamptz not null default now(),
  constraint pk_payment_notifications primary key (id),
  constraint fk_payment_notifications_order foreign key (order_id) references payment_orders(id),
  constraint ck_payment_notifications_provider check (provider in ('wechat_pay', 'alipay'))
);

comment on table payment_notifications is '支付回调记录表';
comment on column payment_notifications.id is '回调记录 ID';
comment on column payment_notifications.order_id is '订单 ID';
comment on column payment_notifications.provider is '支付渠道：wechat_pay/alipay';
comment on column payment_notifications.provider_trade_no is '第三方交易号';
comment on column payment_notifications.notify_payload is '回调原始内容';
comment on column payment_notifications.signature_valid is '签名是否通过';
comment on column payment_notifications.handled is '是否处理完成';
comment on column payment_notifications.received_at is '接收时间';

create index if not exists idx_payment_notifications_order on payment_notifications(order_id);
create index if not exists idx_payment_notifications_provider_trade_no on payment_notifications(provider, provider_trade_no);

create table if not exists media_assets (
  id bigint generated by default as identity,
  media_type varchar(30) not null,
  url varchar(500) not null,
  language varchar(10),
  duration_ms integer,
  file_size bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_media_assets primary key (id),
  constraint ck_media_assets_media_type check (media_type in ('audio', 'image', 'video')),
  constraint ck_media_assets_language check (language is null or language in ('zh', 'ru', 'en')),
  constraint ck_media_assets_duration check (duration_ms is null or duration_ms >= 0),
  constraint ck_media_assets_file_size check (file_size is null or file_size >= 0)
);

comment on table media_assets is '媒体资源表';
comment on column media_assets.id is '媒体 ID';
comment on column media_assets.media_type is '媒体类型：audio/image/video';
comment on column media_assets.url is '资源地址';
comment on column media_assets.language is '资源语言：zh/ru/en，可为空';
comment on column media_assets.duration_ms is '音视频时长，毫秒';
comment on column media_assets.file_size is '文件大小，字节';
comment on column media_assets.created_at is '创建时间';
comment on column media_assets.updated_at is '更新时间';

create index if not exists idx_media_assets_type on media_assets(media_type);

create table if not exists vocab_lists (
  id bigint generated by default as identity,
  name varchar(100) not null,
  list_type varchar(30) not null,
  level varchar(20),
  description text,
  sort_order integer not null default 0,
  status varchar(30) not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_vocab_lists primary key (id),
  constraint ck_vocab_lists_type check (list_type in ('HSK', 'YCT', 'category', 'professional', 'custom')),
  constraint ck_vocab_lists_status check (status in ('active', 'inactive'))
);

comment on table vocab_lists is '词汇表';
comment on column vocab_lists.id is '词汇表 ID';
comment on column vocab_lists.name is '词汇表名称';
comment on column vocab_lists.list_type is '词汇表类型：HSK/YCT/category/professional/custom';
comment on column vocab_lists.level is '级别，如 HSK1、YCT6';
comment on column vocab_lists.description is '描述';
comment on column vocab_lists.sort_order is '排序';
comment on column vocab_lists.status is '状态：active/inactive';
comment on column vocab_lists.created_at is '创建时间';
comment on column vocab_lists.updated_at is '更新时间';

create index if not exists idx_vocab_lists_type_level on vocab_lists(list_type, level);
create index if not exists idx_vocab_lists_status_order on vocab_lists(status, sort_order);

create table if not exists vocab_items (
  id bigint generated by default as identity,
  vocab_list_id bigint not null,
  hanzi varchar(100) not null,
  pinyin varchar(200),
  meaning_en text,
  meaning_ru text,
  example_sentence text,
  audio_asset_id bigint,
  sort_order integer not null default 0,
  status varchar(30) not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_vocab_items primary key (id),
  constraint fk_vocab_items_list foreign key (vocab_list_id) references vocab_lists(id),
  constraint fk_vocab_items_audio foreign key (audio_asset_id) references media_assets(id),
  constraint ck_vocab_items_status check (status in ('active', 'inactive'))
);

comment on table vocab_items is '词汇表条目';
comment on column vocab_items.id is '词汇 ID';
comment on column vocab_items.vocab_list_id is '词汇表 ID';
comment on column vocab_items.hanzi is '汉字';
comment on column vocab_items.pinyin is '拼音';
comment on column vocab_items.meaning_en is '英语释义';
comment on column vocab_items.meaning_ru is '俄语释义';
comment on column vocab_items.example_sentence is '例句';
comment on column vocab_items.audio_asset_id is '汉语读音音频';
comment on column vocab_items.sort_order is '排序';
comment on column vocab_items.status is '状态：active/inactive';
comment on column vocab_items.created_at is '创建时间';
comment on column vocab_items.updated_at is '更新时间';

create index if not exists idx_vocab_items_list_order on vocab_items(vocab_list_id, sort_order);
create index if not exists idx_vocab_items_audio on vocab_items(audio_asset_id);
create index if not exists idx_vocab_items_hanzi on vocab_items(hanzi);

create table if not exists classes (
  id bigint generated by default as identity,
  name varchar(100) not null,
  owner_user_id bigint not null,
  description text,
  invite_code varchar(64),
  status varchar(30) not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_classes primary key (id),
  constraint fk_classes_owner foreign key (owner_user_id) references users(id),
  constraint uq_classes_invite_code unique (invite_code),
  constraint ck_classes_status check (status in ('active', 'archived', 'deleted'))
);

comment on table classes is '班级表';
comment on column classes.id is '班级 ID';
comment on column classes.name is '班级名称';
comment on column classes.owner_user_id is '班级创建者用户 ID';
comment on column classes.description is '班级说明';
comment on column classes.invite_code is '邀请码';
comment on column classes.status is '班级状态：active/archived/deleted';
comment on column classes.created_at is '创建时间';
comment on column classes.updated_at is '更新时间';

create index if not exists idx_classes_owner on classes(owner_user_id);
create index if not exists idx_classes_status on classes(status);

create table if not exists class_members (
  id bigint generated by default as identity,
  class_id bigint not null,
  user_id bigint not null,
  member_role varchar(30) not null default 'member',
  status varchar(30) not null default 'active',
  invited_by_user_id bigint,
  reviewed_by_user_id bigint,
  reviewed_at timestamptz,
  joined_at timestamptz,
  removed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_class_members primary key (id),
  constraint fk_class_members_class foreign key (class_id) references classes(id),
  constraint fk_class_members_user foreign key (user_id) references users(id),
  constraint fk_class_members_invited_by foreign key (invited_by_user_id) references users(id),
  constraint fk_class_members_reviewed_by foreign key (reviewed_by_user_id) references users(id),
  constraint uq_class_members_class_user unique (class_id, user_id),
  constraint ck_class_members_role check (member_role in ('teacher', 'member')),
  constraint ck_class_members_status check (status in ('invited', 'pending_teacher_review', 'active', 'rejected', 'left', 'removed'))
);

comment on table class_members is '班级成员表';
comment on column class_members.id is '成员关系 ID';
comment on column class_members.class_id is '班级 ID';
comment on column class_members.user_id is '用户 ID';
comment on column class_members.member_role is '班级角色：teacher/member';
comment on column class_members.status is '成员状态：invited/pending_teacher_review/active/rejected/left/removed';
comment on column class_members.invited_by_user_id is '邀请人用户 ID';
comment on column class_members.reviewed_by_user_id is '审核老师用户 ID';
comment on column class_members.reviewed_at is '审核时间';
comment on column class_members.joined_at is '加入时间';
comment on column class_members.removed_at is '移除或退出时间';
comment on column class_members.created_at is '创建时间';
comment on column class_members.updated_at is '更新时间';

create index if not exists idx_class_members_class_status on class_members(class_id, status);
create index if not exists idx_class_members_user_status on class_members(user_id, status);
create index if not exists idx_class_members_invited_by on class_members(invited_by_user_id);
create index if not exists idx_class_members_reviewed_by on class_members(reviewed_by_user_id);

create table if not exists study_events (
  id bigint generated by default as identity,
  user_id bigint not null,
  event_type varchar(50) not null,
  target_id bigint,
  result varchar(30),
  duration_seconds integer not null default 0,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint pk_study_events primary key (id),
  constraint fk_study_events_user foreign key (user_id) references users(id),
  constraint ck_study_events_type check (event_type in ('exercise', 'vocab', 'dialogue', 'matching_game')),
  constraint ck_study_events_result check (result is null or result in ('correct', 'wrong', 'completed')),
  constraint ck_study_events_duration check (duration_seconds >= 0)
);

comment on table study_events is '学习行为记录表';
comment on column study_events.id is '行为记录 ID';
comment on column study_events.user_id is '用户 ID';
comment on column study_events.event_type is '行为类型：exercise/vocab/dialogue/matching_game';
comment on column study_events.target_id is '关联业务 ID';
comment on column study_events.result is '结果：correct/wrong/completed';
comment on column study_events.duration_seconds is '学习时长，秒';
comment on column study_events.occurred_at is '发生时间';
comment on column study_events.created_at is '创建时间';

create index if not exists idx_study_events_user_time on study_events(user_id, occurred_at);
create index if not exists idx_study_events_type_time on study_events(event_type, occurred_at);

create table if not exists user_daily_stats (
  id bigint generated by default as identity,
  user_id bigint not null,
  stat_date date not null,
  study_seconds integer not null default 0,
  exercise_count integer not null default 0,
  correct_count integer not null default 0,
  vocab_review_count integer not null default 0,
  dialogue_count integer not null default 0,
  matching_game_count integer not null default 0,
  accuracy_rate numeric(5, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_user_daily_stats primary key (id),
  constraint fk_user_daily_stats_user foreign key (user_id) references users(id),
  constraint uq_user_daily_stats_user_date unique (user_id, stat_date),
  constraint ck_user_daily_stats_non_negative check (
    study_seconds >= 0 and exercise_count >= 0 and correct_count >= 0
    and vocab_review_count >= 0 and dialogue_count >= 0 and matching_game_count >= 0
  ),
  constraint ck_user_daily_stats_accuracy check (accuracy_rate >= 0 and accuracy_rate <= 100)
);

comment on table user_daily_stats is '用户每日统计表';
comment on column user_daily_stats.id is '统计 ID';
comment on column user_daily_stats.user_id is '用户 ID';
comment on column user_daily_stats.stat_date is '统计日期';
comment on column user_daily_stats.study_seconds is '学习时长，秒';
comment on column user_daily_stats.exercise_count is '练习次数';
comment on column user_daily_stats.correct_count is '正确次数';
comment on column user_daily_stats.vocab_review_count is '背词数量';
comment on column user_daily_stats.dialogue_count is '台词训练次数';
comment on column user_daily_stats.matching_game_count is '连连看次数';
comment on column user_daily_stats.accuracy_rate is '当日正确率，0-100';
comment on column user_daily_stats.created_at is '创建时间';
comment on column user_daily_stats.updated_at is '更新时间';

create index if not exists idx_user_daily_stats_date on user_daily_stats(stat_date);

create table if not exists user_learning_summary (
  id bigint generated by default as identity,
  user_id bigint not null,
  total_study_seconds integer not null default 0,
  total_exercise_count integer not null default 0,
  total_correct_count integer not null default 0,
  total_vocab_review_count integer not null default 0,
  current_streak_days integer not null default 0,
  longest_streak_days integer not null default 0,
  overall_accuracy_rate numeric(5, 2) not null default 0,
  last_study_date date,
  updated_at timestamptz not null default now(),
  constraint pk_user_learning_summary primary key (id),
  constraint fk_user_learning_summary_user foreign key (user_id) references users(id),
  constraint uq_user_learning_summary_user unique (user_id),
  constraint ck_user_learning_summary_non_negative check (
    total_study_seconds >= 0 and total_exercise_count >= 0 and total_correct_count >= 0
    and total_vocab_review_count >= 0 and current_streak_days >= 0 and longest_streak_days >= 0
  ),
  constraint ck_user_learning_summary_accuracy check (overall_accuracy_rate >= 0 and overall_accuracy_rate <= 100)
);

comment on table user_learning_summary is '用户学习汇总表';
comment on column user_learning_summary.id is '汇总 ID';
comment on column user_learning_summary.user_id is '用户 ID';
comment on column user_learning_summary.total_study_seconds is '总学习时长，秒';
comment on column user_learning_summary.total_exercise_count is '总练习次数';
comment on column user_learning_summary.total_correct_count is '总正确次数';
comment on column user_learning_summary.total_vocab_review_count is '总背词数量';
comment on column user_learning_summary.current_streak_days is '当前连续学习天数';
comment on column user_learning_summary.longest_streak_days is '最长连续学习天数';
comment on column user_learning_summary.overall_accuracy_rate is '总正确率，0-100';
comment on column user_learning_summary.last_study_date is '最近学习日期';
comment on column user_learning_summary.updated_at is '更新时间';

create table if not exists admin_operation_logs (
  id bigint generated by default as identity,
  admin_user_id bigint,
  action varchar(100) not null,
  target_type varchar(100),
  target_id bigint,
  detail jsonb,
  ip_address varchar(64),
  created_at timestamptz not null default now(),
  constraint pk_admin_operation_logs primary key (id),
  constraint fk_admin_operation_logs_admin_user foreign key (admin_user_id) references admin_users(id)
);

comment on table admin_operation_logs is '后台操作日志表';
comment on column admin_operation_logs.id is '日志 ID';
comment on column admin_operation_logs.admin_user_id is '管理员 ID';
comment on column admin_operation_logs.action is '操作类型';
comment on column admin_operation_logs.target_type is '操作对象类型';
comment on column admin_operation_logs.target_id is '操作对象 ID';
comment on column admin_operation_logs.detail is '操作详情';
comment on column admin_operation_logs.ip_address is 'IP 地址';
comment on column admin_operation_logs.created_at is '创建时间';

create index if not exists idx_admin_operation_logs_admin_time on admin_operation_logs(admin_user_id, created_at);
create index if not exists idx_admin_operation_logs_target on admin_operation_logs(target_type, target_id);

create table if not exists system_configs (
  id bigint generated by default as identity,
  config_key varchar(100) not null,
  config_value text,
  config_group varchar(50) not null,
  description text,
  updated_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_system_configs primary key (id),
  constraint uq_system_configs_key unique (config_key),
  constraint fk_system_configs_updated_by foreign key (updated_by) references admin_users(id),
  constraint ck_system_configs_group check (config_group in ('payment', 'asr', 'membership', 'upload'))
);

comment on table system_configs is '系统配置表';
comment on column system_configs.id is '配置 ID';
comment on column system_configs.config_key is '配置键';
comment on column system_configs.config_value is '配置值';
comment on column system_configs.config_group is '配置分组：payment/asr/membership/upload';
comment on column system_configs.description is '配置说明';
comment on column system_configs.updated_by is '更新管理员 ID';
comment on column system_configs.created_at is '创建时间';
comment on column system_configs.updated_at is '更新时间';

create index if not exists idx_system_configs_group on system_configs(config_group);
create index if not exists idx_system_configs_updated_by on system_configs(updated_by);
