create table if not exists vocab_list_items (
    id bigint generated by default as identity,
    vocab_list_id bigint not null,
    vocab_item_id bigint not null,
    sort_order integer not null default 0,
    status varchar(30) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint pk_vocab_list_items primary key (id),
    constraint fk_vocab_list_items_list foreign key (vocab_list_id) references vocab_lists(id),
    constraint fk_vocab_list_items_item foreign key (vocab_item_id) references vocab_items(id),
    constraint uq_vocab_list_items_list_item unique (vocab_list_id, vocab_item_id),
    constraint ck_vocab_list_items_status check (status in ('active', 'inactive'))
);

comment on table vocab_list_items is '词汇表与全局词汇条目的归属关系';
comment on column vocab_list_items.vocab_list_id is '词汇表ID';
comment on column vocab_list_items.vocab_item_id is '词汇条目ID';
comment on column vocab_list_items.sort_order is '该词汇在当前词汇表内的排序';
comment on column vocab_list_items.status is '归属状态：active/inactive';

insert into vocab_list_items (vocab_list_id, vocab_item_id, sort_order, status, created_at, updated_at)
select vocab_list_id, id, coalesce(sort_order, 0), coalesce(status, 'active'), created_at, updated_at
from vocab_items
where vocab_list_id is not null
on conflict (vocab_list_id, vocab_item_id) do nothing;

alter table vocab_items alter column vocab_list_id drop not null;
comment on column vocab_items.vocab_list_id is '兼容字段：主词汇表ID，新逻辑以 vocab_list_items 为准';
comment on column vocab_items.sort_order is '兼容字段：默认排序，新逻辑可在 vocab_list_items 中按词汇表覆盖';

drop index if exists idx_vocab_items_list_order;
create index if not exists idx_vocab_list_items_list_order on vocab_list_items(vocab_list_id, sort_order, vocab_item_id);
create index if not exists idx_vocab_list_items_item on vocab_list_items(vocab_item_id);
create index if not exists idx_vocab_items_status_hanzi on vocab_items(status, hanzi);

create table if not exists exercise_set_items (
    id bigint generated by default as identity,
    exercise_set_id bigint not null,
    sentence_exercise_id bigint not null,
    sort_order integer not null default 0,
    status varchar(30) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint pk_exercise_set_items primary key (id),
    constraint fk_exercise_set_items_set foreign key (exercise_set_id) references exercise_sets(id),
    constraint fk_exercise_set_items_exercise foreign key (sentence_exercise_id) references sentence_exercises(id),
    constraint uq_exercise_set_items_set_exercise unique (exercise_set_id, sentence_exercise_id),
    constraint ck_exercise_set_items_status check (status in ('active', 'inactive'))
);

comment on table exercise_set_items is '题组与全局句子题的归属关系';
comment on column exercise_set_items.exercise_set_id is '题组ID';
comment on column exercise_set_items.sentence_exercise_id is '句子题ID';
comment on column exercise_set_items.sort_order is '该句子题在当前题组内的排序';
comment on column exercise_set_items.status is '归属状态：active/inactive';

insert into exercise_set_items (exercise_set_id, sentence_exercise_id, sort_order, status, created_at, updated_at)
select exercise_set_id, id, coalesce(sort_order, 0), coalesce(status, 'active'), created_at, updated_at
from sentence_exercises
where exercise_set_id is not null
on conflict (exercise_set_id, sentence_exercise_id) do nothing;

alter table sentence_exercises alter column exercise_set_id drop not null;
comment on column sentence_exercises.exercise_set_id is '兼容字段：题组ID，新逻辑以 exercise_set_items 为准';
comment on column sentence_exercises.sort_order is '兼容字段：默认排序，新逻辑可在 exercise_set_items 中按题组覆盖';

drop index if exists idx_sentence_exercises_set_order;
create index if not exists idx_exercise_set_items_set_order on exercise_set_items(exercise_set_id, sort_order, sentence_exercise_id);
create index if not exists idx_exercise_set_items_exercise on exercise_set_items(sentence_exercise_id);
create index if not exists idx_sentence_exercises_status_answer on sentence_exercises(status, hanzi_answer);
