create table if not exists vocab_item_stroke_assets (
    id bigint generated by default as identity,
    vocab_item_id bigint not null,
    media_asset_id bigint not null,
    title varchar(100),
    sort_order integer not null default 0,
    status varchar(30) not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint pk_vocab_item_stroke_assets primary key (id),
    constraint fk_vocab_item_stroke_assets_item foreign key (vocab_item_id) references vocab_items(id),
    constraint fk_vocab_item_stroke_assets_media foreign key (media_asset_id) references media_assets(id),
    constraint uq_vocab_item_stroke_assets_item_media unique (vocab_item_id, media_asset_id),
    constraint ck_vocab_item_stroke_assets_status check (status in ('active', 'inactive'))
);

comment on table vocab_item_stroke_assets is '词汇条目的汉字笔画演示图片/GIF列表';
comment on column vocab_item_stroke_assets.vocab_item_id is '词汇条目ID';
comment on column vocab_item_stroke_assets.media_asset_id is '媒体资源ID，支持图片或GIF';
comment on column vocab_item_stroke_assets.title is '演示图标题，可用于多字词区分';
comment on column vocab_item_stroke_assets.sort_order is '展示顺序';
comment on column vocab_item_stroke_assets.status is '状态：active/inactive';

insert into vocab_item_stroke_assets (vocab_item_id, media_asset_id, title, sort_order, status, created_at, updated_at)
select id, stroke_order_asset_id, null, 0, 'active', created_at, updated_at
from vocab_items
where stroke_order_asset_id is not null
on conflict (vocab_item_id, media_asset_id) do nothing;

create index if not exists idx_vocab_item_stroke_assets_item_order
  on vocab_item_stroke_assets(vocab_item_id, sort_order, id);

create index if not exists idx_vocab_item_stroke_assets_media
  on vocab_item_stroke_assets(media_asset_id);
