-- Complete schema for XC Chinese Learning Platform.
-- Completes the tables defined in 基本设计.md section 6 and aligns timestamp
-- columns with AGENTS.md database rules.

alter table if exists payment_notifications
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

comment on column payment_notifications.created_at is '创建时间';
comment on column payment_notifications.updated_at is '更新时间';

alter table if exists study_events
  add column if not exists updated_at timestamptz not null default now();

comment on column study_events.updated_at is '更新时间';

alter table if exists user_learning_summary
  add column if not exists created_at timestamptz not null default now();

comment on column user_learning_summary.created_at is '创建时间';

alter table if exists admin_operation_logs
  add column if not exists updated_at timestamptz not null default now();

comment on column admin_operation_logs.updated_at is '更新时间';

create table if not exists admin_roles (
  id bigint generated by default as identity,
  role_code varchar(50) not null,
  role_name varchar(100) not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_admin_roles primary key (id),
  constraint uq_admin_roles_code unique (role_code),
  constraint ck_admin_roles_code_not_blank check (length(trim(role_code)) > 0)
);

comment on table admin_roles is '后台角色表';
comment on column admin_roles.id is '角色 ID';
comment on column admin_roles.role_code is '角色编码';
comment on column admin_roles.role_name is '角色名称';
comment on column admin_roles.description is '角色说明';
comment on column admin_roles.created_at is '创建时间';
comment on column admin_roles.updated_at is '更新时间';

create index if not exists idx_admin_roles_created_at on admin_roles(created_at);

create table if not exists admin_permissions (
  id bigint generated by default as identity,
  permission_code varchar(100) not null,
  permission_name varchar(100) not null,
  module_name varchar(100) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_admin_permissions primary key (id),
  constraint uq_admin_permissions_code unique (permission_code),
  constraint ck_admin_permissions_code_not_blank check (length(trim(permission_code)) > 0)
);

comment on table admin_permissions is '后台权限表';
comment on column admin_permissions.id is '权限 ID';
comment on column admin_permissions.permission_code is '权限编码，建议格式为 模块:资源:动作';
comment on column admin_permissions.permission_name is '权限名称';
comment on column admin_permissions.module_name is '所属模块';
comment on column admin_permissions.created_at is '创建时间';
comment on column admin_permissions.updated_at is '更新时间';

create index if not exists idx_admin_permissions_module on admin_permissions(module_name);

create table if not exists admin_role_permissions (
  id bigint generated by default as identity,
  role_id bigint not null,
  permission_id bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_admin_role_permissions primary key (id),
  constraint fk_admin_role_permissions_role foreign key (role_id) references admin_roles(id),
  constraint fk_admin_role_permissions_permission foreign key (permission_id) references admin_permissions(id),
  constraint uq_admin_role_permissions_role_permission unique (role_id, permission_id)
);

comment on table admin_role_permissions is '后台角色权限关联表';
comment on column admin_role_permissions.id is '关联 ID';
comment on column admin_role_permissions.role_id is '角色 ID';
comment on column admin_role_permissions.permission_id is '权限 ID';
comment on column admin_role_permissions.created_at is '创建时间';
comment on column admin_role_permissions.updated_at is '更新时间';

create index if not exists idx_admin_role_permissions_permission on admin_role_permissions(permission_id);

create table if not exists admin_user_roles (
  id bigint generated by default as identity,
  admin_user_id bigint not null,
  role_id bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_admin_user_roles primary key (id),
  constraint fk_admin_user_roles_admin_user foreign key (admin_user_id) references admin_users(id),
  constraint fk_admin_user_roles_role foreign key (role_id) references admin_roles(id),
  constraint uq_admin_user_roles_user_role unique (admin_user_id, role_id)
);

comment on table admin_user_roles is '后台管理员角色关联表';
comment on column admin_user_roles.id is '关联 ID';
comment on column admin_user_roles.admin_user_id is '管理员 ID';
comment on column admin_user_roles.role_id is '角色 ID';
comment on column admin_user_roles.created_at is '创建时间';
comment on column admin_user_roles.updated_at is '更新时间';

create index if not exists idx_admin_user_roles_role on admin_user_roles(role_id);

create table if not exists user_vocab_progress (
  id bigint generated by default as identity,
  user_id bigint not null,
  vocab_list_id bigint not null,
  current_index integer not null default 0,
  last_vocab_item_id bigint,
  reviewed_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_user_vocab_progress primary key (id),
  constraint fk_user_vocab_progress_user foreign key (user_id) references users(id),
  constraint fk_user_vocab_progress_list foreign key (vocab_list_id) references vocab_lists(id),
  constraint fk_user_vocab_progress_last_item foreign key (last_vocab_item_id) references vocab_items(id),
  constraint uq_user_vocab_progress_user_list unique (user_id, vocab_list_id),
  constraint ck_user_vocab_progress_non_negative check (current_index >= 0 and reviewed_count >= 0)
);

comment on table user_vocab_progress is '背词进度表';
comment on column user_vocab_progress.id is '进度 ID';
comment on column user_vocab_progress.user_id is '用户 ID';
comment on column user_vocab_progress.vocab_list_id is '词汇表 ID';
comment on column user_vocab_progress.current_index is '当前背诵位置';
comment on column user_vocab_progress.last_vocab_item_id is '最近词汇 ID';
comment on column user_vocab_progress.reviewed_count is '已学习数量';
comment on column user_vocab_progress.created_at is '创建时间';
comment on column user_vocab_progress.updated_at is '更新时间';

create index if not exists idx_user_vocab_progress_list on user_vocab_progress(vocab_list_id);
create index if not exists idx_user_vocab_progress_last_item on user_vocab_progress(last_vocab_item_id);

create table if not exists user_vocab_favorites (
  id bigint generated by default as identity,
  user_id bigint not null,
  vocab_item_id bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_user_vocab_favorites primary key (id),
  constraint fk_user_vocab_favorites_user foreign key (user_id) references users(id),
  constraint fk_user_vocab_favorites_item foreign key (vocab_item_id) references vocab_items(id),
  constraint uq_user_vocab_favorites_user_item unique (user_id, vocab_item_id)
);

comment on table user_vocab_favorites is '词汇收藏表';
comment on column user_vocab_favorites.id is '收藏 ID';
comment on column user_vocab_favorites.user_id is '用户 ID';
comment on column user_vocab_favorites.vocab_item_id is '词汇 ID';
comment on column user_vocab_favorites.created_at is '收藏时间';
comment on column user_vocab_favorites.updated_at is '更新时间';

create index if not exists idx_user_vocab_favorites_item on user_vocab_favorites(vocab_item_id);

create table if not exists exercise_sets (
  id bigint generated by default as identity,
  title varchar(200) not null,
  exercise_type varchar(50) not null,
  level varchar(50),
  status varchar(30) not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_exercise_sets primary key (id),
  constraint ck_exercise_sets_type check (exercise_type in ('audio_order', 'audio_dictation', 'pinyin_dictation', 'translation_order')),
  constraint ck_exercise_sets_status check (status in ('active', 'inactive'))
);

comment on table exercise_sets is '题组表';
comment on column exercise_sets.id is '题组 ID';
comment on column exercise_sets.title is '题组标题';
comment on column exercise_sets.exercise_type is '题型：audio_order/audio_dictation/pinyin_dictation/translation_order';
comment on column exercise_sets.level is '难度或级别';
comment on column exercise_sets.status is '状态：active/inactive';
comment on column exercise_sets.created_at is '创建时间';
comment on column exercise_sets.updated_at is '更新时间';

create index if not exists idx_exercise_sets_type_level on exercise_sets(exercise_type, level);
create index if not exists idx_exercise_sets_status on exercise_sets(status);

create table if not exists sentence_exercises (
  id bigint generated by default as identity,
  exercise_set_id bigint not null,
  exercise_type varchar(50) not null,
  hanzi_answer text not null,
  pinyin_prompt text,
  translation_en text,
  translation_ru text,
  audio_zh_asset_id bigint,
  explanation text,
  sort_order integer not null default 0,
  status varchar(30) not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_sentence_exercises primary key (id),
  constraint fk_sentence_exercises_set foreign key (exercise_set_id) references exercise_sets(id),
  constraint fk_sentence_exercises_audio foreign key (audio_zh_asset_id) references media_assets(id),
  constraint ck_sentence_exercises_type check (exercise_type in ('audio_order', 'audio_dictation', 'pinyin_dictation', 'translation_order')),
  constraint ck_sentence_exercises_status check (status in ('active', 'inactive'))
);

comment on table sentence_exercises is '句子题表';
comment on column sentence_exercises.id is '题目 ID';
comment on column sentence_exercises.exercise_set_id is '题组 ID';
comment on column sentence_exercises.exercise_type is '题型';
comment on column sentence_exercises.hanzi_answer is '汉语标准答案';
comment on column sentence_exercises.pinyin_prompt is '拼音提示';
comment on column sentence_exercises.translation_en is '英语翻译或提示';
comment on column sentence_exercises.translation_ru is '俄语翻译或提示';
comment on column sentence_exercises.audio_zh_asset_id is '汉语句子录音';
comment on column sentence_exercises.explanation is '解析';
comment on column sentence_exercises.sort_order is '顺序';
comment on column sentence_exercises.status is '状态：active/inactive';
comment on column sentence_exercises.created_at is '创建时间';
comment on column sentence_exercises.updated_at is '更新时间';

create index if not exists idx_sentence_exercises_set_order on sentence_exercises(exercise_set_id, sort_order);
create index if not exists idx_sentence_exercises_status on sentence_exercises(status);
create index if not exists idx_sentence_exercises_audio on sentence_exercises(audio_zh_asset_id);

create table if not exists sentence_word_options (
  id bigint generated by default as identity,
  exercise_id bigint not null,
  word_text varchar(100) not null,
  correct_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_sentence_word_options primary key (id),
  constraint fk_sentence_word_options_exercise foreign key (exercise_id) references sentence_exercises(id),
  constraint uq_sentence_word_options_exercise_order unique (exercise_id, correct_order),
  constraint ck_sentence_word_options_order check (correct_order > 0)
);

comment on table sentence_word_options is '句子排序词块表';
comment on column sentence_word_options.id is '词块 ID';
comment on column sentence_word_options.exercise_id is '题目 ID';
comment on column sentence_word_options.word_text is '词块内容';
comment on column sentence_word_options.correct_order is '正确顺序';
comment on column sentence_word_options.created_at is '创建时间';
comment on column sentence_word_options.updated_at is '更新时间';

create index if not exists idx_sentence_word_options_exercise on sentence_word_options(exercise_id);

create table if not exists exercise_attempts (
  id bigint generated by default as identity,
  user_id bigint not null,
  exercise_id bigint not null,
  exercise_type varchar(50) not null,
  answer_text text,
  is_correct boolean not null,
  error_detail jsonb,
  showed_answer boolean not null default false,
  translation_language varchar(10),
  answered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_exercise_attempts primary key (id),
  constraint fk_exercise_attempts_user foreign key (user_id) references users(id),
  constraint fk_exercise_attempts_exercise foreign key (exercise_id) references sentence_exercises(id),
  constraint ck_exercise_attempts_type check (exercise_type in ('audio_order', 'audio_dictation', 'pinyin_dictation', 'translation_order')),
  constraint ck_exercise_attempts_translation_language check (translation_language is null or translation_language in ('ru', 'en'))
);

comment on table exercise_attempts is '练习作答记录表';
comment on column exercise_attempts.id is '作答记录 ID';
comment on column exercise_attempts.user_id is '用户 ID';
comment on column exercise_attempts.exercise_id is '题目 ID';
comment on column exercise_attempts.exercise_type is '题型';
comment on column exercise_attempts.answer_text is '用户答案，排序题可保存 JSON';
comment on column exercise_attempts.is_correct is '是否正确';
comment on column exercise_attempts.error_detail is '错误位置或差异';
comment on column exercise_attempts.showed_answer is '是否查看答案';
comment on column exercise_attempts.translation_language is '本次翻译语言';
comment on column exercise_attempts.answered_at is '作答时间';
comment on column exercise_attempts.created_at is '创建时间';
comment on column exercise_attempts.updated_at is '更新时间';

create index if not exists idx_exercise_attempts_user_answered on exercise_attempts(user_id, answered_at);
create index if not exists idx_exercise_attempts_exercise on exercise_attempts(exercise_id);

create table if not exists video_materials (
  id bigint generated by default as identity,
  title varchar(200) not null,
  material_type varchar(30) not null,
  description text,
  cover_asset_id bigint,
  status varchar(30) not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_video_materials primary key (id),
  constraint fk_video_materials_cover foreign key (cover_asset_id) references media_assets(id),
  constraint ck_video_materials_type check (material_type in ('drama', 'short_video', 'cartoon')),
  constraint ck_video_materials_status check (status in ('active', 'inactive'))
);

comment on table video_materials is '台词材料表';
comment on column video_materials.id is '材料 ID';
comment on column video_materials.title is '材料标题';
comment on column video_materials.material_type is '材料类型：drama/short_video/cartoon';
comment on column video_materials.description is '描述';
comment on column video_materials.cover_asset_id is '封面';
comment on column video_materials.status is '状态：active/inactive';
comment on column video_materials.created_at is '创建时间';
comment on column video_materials.updated_at is '更新时间';

create index if not exists idx_video_materials_type_status on video_materials(material_type, status);
create index if not exists idx_video_materials_cover on video_materials(cover_asset_id);

create table if not exists dialogue_lines (
  id bigint generated by default as identity,
  material_id bigint not null,
  line_no integer not null,
  hanzi_text text not null,
  pinyin_text text,
  translation_en text,
  translation_ru text,
  audio_asset_id bigint,
  start_ms integer,
  end_ms integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_dialogue_lines primary key (id),
  constraint fk_dialogue_lines_material foreign key (material_id) references video_materials(id),
  constraint fk_dialogue_lines_audio foreign key (audio_asset_id) references media_assets(id),
  constraint uq_dialogue_lines_material_line unique (material_id, line_no),
  constraint ck_dialogue_lines_line_no check (line_no > 0),
  constraint ck_dialogue_lines_time_range check (
    (start_ms is null or start_ms >= 0)
    and (end_ms is null or end_ms >= 0)
    and (start_ms is null or end_ms is null or end_ms >= start_ms)
  )
);

comment on table dialogue_lines is '台词行表';
comment on column dialogue_lines.id is '台词 ID';
comment on column dialogue_lines.material_id is '材料 ID';
comment on column dialogue_lines.line_no is '台词顺序';
comment on column dialogue_lines.hanzi_text is '汉语台词';
comment on column dialogue_lines.pinyin_text is '拼音';
comment on column dialogue_lines.translation_en is '英语翻译';
comment on column dialogue_lines.translation_ru is '俄语翻译';
comment on column dialogue_lines.audio_asset_id is '台词音频';
comment on column dialogue_lines.start_ms is '开始时间，毫秒';
comment on column dialogue_lines.end_ms is '结束时间，毫秒';
comment on column dialogue_lines.created_at is '创建时间';
comment on column dialogue_lines.updated_at is '更新时间';

create index if not exists idx_dialogue_lines_material_order on dialogue_lines(material_id, line_no);
create index if not exists idx_dialogue_lines_audio on dialogue_lines(audio_asset_id);

create table if not exists dialogue_line_vocab (
  id bigint generated by default as identity,
  dialogue_line_id bigint not null,
  vocab_item_id bigint,
  word_text varchar(100) not null,
  pinyin varchar(200),
  meaning_en text,
  meaning_ru text,
  explanation text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_dialogue_line_vocab primary key (id),
  constraint fk_dialogue_line_vocab_line foreign key (dialogue_line_id) references dialogue_lines(id),
  constraint fk_dialogue_line_vocab_item foreign key (vocab_item_id) references vocab_items(id)
);

comment on table dialogue_line_vocab is '台词词汇解析表';
comment on column dialogue_line_vocab.id is '解析 ID';
comment on column dialogue_line_vocab.dialogue_line_id is '台词 ID';
comment on column dialogue_line_vocab.vocab_item_id is '词汇 ID，可为空';
comment on column dialogue_line_vocab.word_text is '词语';
comment on column dialogue_line_vocab.pinyin is '拼音';
comment on column dialogue_line_vocab.meaning_en is '英语释义';
comment on column dialogue_line_vocab.meaning_ru is '俄语释义';
comment on column dialogue_line_vocab.explanation is '补充说明';
comment on column dialogue_line_vocab.created_at is '创建时间';
comment on column dialogue_line_vocab.updated_at is '更新时间';

create index if not exists idx_dialogue_line_vocab_line on dialogue_line_vocab(dialogue_line_id);
create index if not exists idx_dialogue_line_vocab_item on dialogue_line_vocab(vocab_item_id);

create table if not exists asr_jobs (
  id bigint generated by default as identity,
  user_id bigint not null,
  audio_asset_id bigint not null,
  engine_name varchar(100) not null,
  status varchar(30) not null default 'pending',
  recognized_text text,
  error_message text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_asr_jobs primary key (id),
  constraint fk_asr_jobs_user foreign key (user_id) references users(id),
  constraint fk_asr_jobs_audio foreign key (audio_asset_id) references media_assets(id),
  constraint ck_asr_jobs_status check (status in ('pending', 'processing', 'succeeded', 'failed')),
  constraint ck_asr_jobs_time_range check (started_at is null or finished_at is null or finished_at >= started_at)
);

comment on table asr_jobs is '本地语音识别任务表';
comment on column asr_jobs.id is 'ASR 任务 ID';
comment on column asr_jobs.user_id is '用户 ID';
comment on column asr_jobs.audio_asset_id is '待识别录音';
comment on column asr_jobs.engine_name is '本地识别引擎名称';
comment on column asr_jobs.status is '任务状态：pending/processing/succeeded/failed';
comment on column asr_jobs.recognized_text is '识别结果';
comment on column asr_jobs.error_message is '失败原因';
comment on column asr_jobs.started_at is '开始时间';
comment on column asr_jobs.finished_at is '完成时间';
comment on column asr_jobs.created_at is '创建时间';
comment on column asr_jobs.updated_at is '更新时间';

create index if not exists idx_asr_jobs_user_status on asr_jobs(user_id, status, created_at);
create index if not exists idx_asr_jobs_audio on asr_jobs(audio_asset_id);
create index if not exists idx_asr_jobs_status on asr_jobs(status);

create table if not exists speech_records (
  id bigint generated by default as identity,
  user_id bigint not null,
  dialogue_line_id bigint not null,
  audio_asset_id bigint not null,
  recognized_text text,
  compare_result jsonb,
  score numeric(5, 2),
  asr_job_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_speech_records primary key (id),
  constraint fk_speech_records_user foreign key (user_id) references users(id),
  constraint fk_speech_records_line foreign key (dialogue_line_id) references dialogue_lines(id),
  constraint fk_speech_records_audio foreign key (audio_asset_id) references media_assets(id),
  constraint fk_speech_records_asr_job foreign key (asr_job_id) references asr_jobs(id),
  constraint uq_speech_records_asr_job unique (asr_job_id),
  constraint ck_speech_records_score check (score is null or (score >= 0 and score <= 100))
);

comment on table speech_records is '录音与识别表';
comment on column speech_records.id is '录音记录 ID';
comment on column speech_records.user_id is '用户 ID';
comment on column speech_records.dialogue_line_id is '台词 ID';
comment on column speech_records.audio_asset_id is '用户录音';
comment on column speech_records.recognized_text is '语音识别出的汉字';
comment on column speech_records.compare_result is '与标准台词对比结果';
comment on column speech_records.score is '评分，0-100';
comment on column speech_records.asr_job_id is '本地 ASR 任务 ID';
comment on column speech_records.created_at is '创建时间';
comment on column speech_records.updated_at is '更新时间';

create index if not exists idx_speech_records_user_time on speech_records(user_id, created_at);
create index if not exists idx_speech_records_line on speech_records(dialogue_line_id);
create index if not exists idx_speech_records_audio on speech_records(audio_asset_id);

create table if not exists matching_game_sessions (
  id bigint generated by default as identity,
  user_id bigint not null,
  source_type varchar(30) not null,
  vocab_list_id bigint,
  meaning_language varchar(10) not null,
  difficulty varchar(20) not null,
  total_pairs integer not null,
  matched_pairs integer not null default 0,
  wrong_count integer not null default 0,
  elapsed_seconds integer not null default 0,
  status varchar(30) not null default 'playing',
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint pk_matching_game_sessions primary key (id),
  constraint fk_matching_game_sessions_user foreign key (user_id) references users(id),
  constraint fk_matching_game_sessions_vocab_list foreign key (vocab_list_id) references vocab_lists(id),
  constraint ck_matching_game_sessions_source check (source_type in ('vocab_list', 'favorites')),
  constraint ck_matching_game_sessions_source_ref check (source_type <> 'vocab_list' or vocab_list_id is not null),
  constraint ck_matching_game_sessions_meaning_language check (meaning_language in ('ru', 'en')),
  constraint ck_matching_game_sessions_difficulty check (difficulty in ('4x4', '7x7', '10x10')),
  constraint ck_matching_game_sessions_status check (status in ('playing', 'completed', 'abandoned')),
  constraint ck_matching_game_sessions_counts check (
    total_pairs > 0 and matched_pairs >= 0 and matched_pairs <= total_pairs
    and wrong_count >= 0 and elapsed_seconds >= 0
  )
);

comment on table matching_game_sessions is '连连看游戏记录表';
comment on column matching_game_sessions.id is '游戏记录 ID';
comment on column matching_game_sessions.user_id is '用户 ID';
comment on column matching_game_sessions.source_type is '词汇来源：vocab_list/favorites';
comment on column matching_game_sessions.vocab_list_id is '词汇表 ID，可为空';
comment on column matching_game_sessions.meaning_language is '释义语言：ru/en';
comment on column matching_game_sessions.difficulty is '难度：4x4/7x7/10x10';
comment on column matching_game_sessions.total_pairs is '总匹配数';
comment on column matching_game_sessions.matched_pairs is '成功匹配数';
comment on column matching_game_sessions.wrong_count is '错误次数';
comment on column matching_game_sessions.elapsed_seconds is '用时，秒';
comment on column matching_game_sessions.status is '状态：playing/completed/abandoned';
comment on column matching_game_sessions.created_at is '创建时间';
comment on column matching_game_sessions.completed_at is '完成时间';
comment on column matching_game_sessions.updated_at is '更新时间';

create index if not exists idx_matching_game_sessions_user_status on matching_game_sessions(user_id, status, created_at);
create index if not exists idx_matching_game_sessions_vocab_list on matching_game_sessions(vocab_list_id);

create table if not exists content_translations (
  id bigint generated by default as identity,
  entity_type varchar(50) not null,
  entity_id bigint not null,
  field_name varchar(50) not null,
  language varchar(10) not null,
  translated_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_content_translations primary key (id),
  constraint uq_content_translations_entity_field_language unique (entity_type, entity_id, field_name, language),
  constraint ck_content_translations_language check (language in ('zh', 'ru', 'en'))
);

comment on table content_translations is '内容翻译表';
comment on column content_translations.id is '翻译 ID';
comment on column content_translations.entity_type is '资源类型，如 ui/exercise/vocab/material';
comment on column content_translations.entity_id is '资源 ID';
comment on column content_translations.field_name is '字段名';
comment on column content_translations.language is '语言：zh/ru/en';
comment on column content_translations.translated_text is '翻译文本';
comment on column content_translations.created_at is '创建时间';
comment on column content_translations.updated_at is '更新时间';

create index if not exists idx_content_translations_entity on content_translations(entity_type, entity_id);
create index if not exists idx_content_translations_language on content_translations(language);

create table if not exists leaderboard_entries (
  id bigint generated by default as identity,
  period_type varchar(20) not null,
  period_start date not null,
  metric_type varchar(50) not null,
  user_id bigint not null,
  score_value numeric(12, 2) not null,
  rank_no integer not null,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pk_leaderboard_entries primary key (id),
  constraint fk_leaderboard_entries_user foreign key (user_id) references users(id),
  constraint uq_leaderboard_entries_period_metric_user unique (period_type, period_start, metric_type, user_id),
  constraint uq_leaderboard_entries_period_metric_rank unique (period_type, period_start, metric_type, rank_no),
  constraint ck_leaderboard_entries_period check (period_type in ('daily', 'weekly', 'monthly', 'all')),
  constraint ck_leaderboard_entries_metric check (metric_type in ('streak', 'accuracy', 'vocab_count', 'game_score')),
  constraint ck_leaderboard_entries_rank check (rank_no > 0),
  constraint ck_leaderboard_entries_score check (score_value >= 0)
);

comment on table leaderboard_entries is '排行榜表';
comment on column leaderboard_entries.id is '排名 ID';
comment on column leaderboard_entries.period_type is '榜单周期类型：daily/weekly/monthly/all';
comment on column leaderboard_entries.period_start is '榜单周期开始';
comment on column leaderboard_entries.metric_type is '排行指标：streak/accuracy/vocab_count/game_score';
comment on column leaderboard_entries.user_id is '用户 ID';
comment on column leaderboard_entries.score_value is '排行分值';
comment on column leaderboard_entries.rank_no is '排名';
comment on column leaderboard_entries.generated_at is '生成时间';
comment on column leaderboard_entries.created_at is '创建时间';
comment on column leaderboard_entries.updated_at is '更新时间';

create index if not exists idx_leaderboard_entries_period_rank on leaderboard_entries(period_type, period_start, metric_type, rank_no);
create index if not exists idx_leaderboard_entries_user_metric on leaderboard_entries(user_id, metric_type);
